name: Publish Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node v12
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Cache
        uses: actions/cache@master
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install
        run: npm ci

      - name: Audit
        run: npx audit-ci --high

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test coverage
        run: npm run test:cov
        env:
          CI: true

      # Publish to NPMJS Registry
      - name: Setup for publishing to NPM Registry
        uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org/'

      - name: Publish to NPMJS
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@sohailalam2"
          npm config list
          npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # Publish to GitHub Package Registry
      - name: Setup for publishing to GitHub Package Registry
        uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@sohailalam2'

      - name: Publish to Github
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
